### PR TITLE
Show login and register form only for guest users

### PR DESCRIPTION
**Pull request by hailtonsilva**

### CODE REVIEW

**Comment by msurguy** [comment]
@hailtonsilva I think that's a good idea, could you please make sure the formatting is the same as other files and I'll merge this PR.

**Comment by hailtonsilva** [comment]
Ok, I will do that @msurguy ;)

**Comment by hailtonsilva** [comment]
As you asked [here] (https://github.com/CodepadME/laravel-tricks/pull/82), I've changed the code, removing the return.. But keep in mind that I've tested the code locally(with laravel 4.2) and it's not working properly without the return. Check that and if necessary I'll change it again. Thank you

**Comment by wza64210017** [comment]
收到！

**Pull request closed without merging**
