### PR TITLE
Show the login form only for guest users

### PR DESCRIPTION
**Pull request by hailtonsilva**
I think it's now well formatted..

### CODE REVIEW

**Comment by hailtonsilva** [comment]
Wait on @msurguy... I'm currently checking other stuffs in this controller. I'll commit everything together and make the pull request again ok

**Comment by msurguy** [comment]
@hailtonsilva looks good!

**Comment by msurguy** [comment]
@hailtonsilva Thank you!

**Comment by msurguy** [comment]
Actually I think we need to have another PR for that, the thing is that we already have "return" statement in  "redirectIntended" function and "view" function doesn't need a return statement. 

Could you please update you code to:
```
if (Auth::guest()) {
    $this->view('home.login');
}
$this->redirectIntended(route('user.index'));
```
And I will merge it. Also do the same for the other PR please and test on your local first. Thanks!

**Comment by hailtonsilva** [comment]
Code was tested locally with laravel 4.2 and it works. But yes, I understand that, I'll remove the return. Thank you.

**Comment by hailtonsilva** [comment]
Requested changes was changed [here] (https://github.com/CodepadME/laravel-tricks/pull/81)

**Pull request merged**
